Botanical/Areas/Admin/Controllers/CategoryController.cs
using AutoMapper;
using Business.DTOs.Category;
using Business.IServices;
using Business.Services;
using Data.Context;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.SecurityTokenService;

namespace Botanical.Areas.Admin.Controllers
{
    [Area(nameof(Admin))]
    public class CategoryController : Controller
    {
        private readonly ICategoryService _CategoryService;
        private readonly AppDbContext _context;
        private readonly IMapper _mapper;
		public CategoryController(ICategoryService CategoryService, AppDbContext context, IMapper mapper)
		{
            _CategoryService = CategoryService;
			_context = context;
			_mapper = mapper;
		}

		public async Task<IActionResult> Index()
        {
            var categories = await _CategoryService.GetAllCategoryAsync();
            return View(categories);
        }

        [HttpGet]
        public IActionResult AddCategory()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddCategory(CreateCategoryDTO addCategoryDTO)
        {
            if (!ModelState.IsValid)
            {
                return View(addCategoryDTO);
            }


            try
            {
                await _CategoryService.AddCategory(addCategoryDTO);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(addCategoryDTO);
            }
            //catch (Exception ex)
            //{
            //    // General exception (file upload, server errors, etc.)
            //    ModelState.AddModelError(string.Empty, ex.Message);
            //    return View(addCategoryDTO);
            //}
        }

        [HttpPost]
        public async Task<IActionResult> DeleteCategory(Guid id)
        {
            try
            {
                await _CategoryService.DeleteCategory(id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return BadRequest(new { message = ex.Message });
            }
        }

        [HttpPost]
        public async Task<IActionResult> RestoreCategory(Guid id)
        {
            try
            {
                await _CategoryService.RestoreCategory(id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return BadRequest(new { message = ex.Message });
            }
        }

        [HttpGet]
        public async Task<IActionResult> EditCategory(Guid Id)
        {
            try
            {
                var category = await _CategoryService.GetCategoryById(Id);

                if (category == null)
                {
                    return NotFound("Category not found.");
                }

                var updateCategoryDTO = new CreateCategoryDTO
                {
                    Id = category.Id,
                    Name = category.Name,
                    ImgPath = category.ImgPath,
                };

                return View(updateCategoryDTO);
            }
            catch (Exception ex)
            {
                // Log the exception (ex) here if necessary
                return View("EditCategory", ex.Message);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditCategoryAsync(Guid id,  CreateCategoryDTO updateCategoryDTO)
        {
            if (!ModelState.IsValid)
            {

				return View(updateCategoryDTO);
            }

           
                await _CategoryService.EditCategory(id, updateCategoryDTO);
                TempData["Success"] = "Category updated successfully!";
                return RedirectToAction("Index");  
            
        }

    }
}

Botanical/Areas/Admin/Controllers/SliderController.cs
using AutoMapper;
using Business.DTOs.Slider;
using Business.IServices;
using Data.Context;
using Data.Services;
using Microsoft.AspNetCore.Mvc;

namespace Botanical.Areas.Admin.Controllers
{
    [Area(nameof(Admin))]
    public class SliderController : Controller
    {
        private readonly ISliderService _SliderService;
        private readonly AppDbContext _context;
        private readonly IMapper _mapper;
        public SliderController(ISliderService SliderService, AppDbContext context, IMapper mapper)
        {
            _SliderService = SliderService;
            _context = context;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var sliders = await _SliderService.GetAllSliderAsync();
            return View(sliders);
        }

        [HttpGet]
        public IActionResult AddSlider()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddSlider(CreateSliderDTO addSliderDTO)
        {
            if (!ModelState.IsValid)
            {
                return View(addSliderDTO);
            }


            try
            {
                await _SliderService.AddSlider(addSliderDTO);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(addSliderDTO);
            }
            //catch (Exception ex)
            //{
            //    // General exception (file upload, server errors, etc.)
            //    ModelState.AddModelError(string.Empty, ex.Message);
            //    return View(addSliderDTO);
            //}
        }


        [HttpPost]
        public async Task<IActionResult> DeleteSlider(Guid id)
        {
            try
            {
                await _SliderService.DeleteSlider(id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return BadRequest(new { message = ex.Message });
            }
        }

        [HttpPost]
        public async Task<IActionResult> RestoreSlider(Guid id)
        {
            try
            {
                await _SliderService.RestoreSlider(id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return BadRequest(new { message = ex.Message });
            }
        }

        [HttpGet]
        public async Task<IActionResult> EditSlider(Guid Id)
        {
            try
            {
                var Slider = await _SliderService.GetSliderById(Id);

                if (Slider == null)
                {
                    return NotFound("Slider not found.");
                }

                var updateSliderDTO = new CreateSliderDTO
                {
                    Id = Slider.Id,
                    Description = Slider.Description,
                    Title = Slider.Title,
                    SubTitle = Slider.SubTitle,
                    ImagePath = Slider.ImagePath,
                };

                return View(updateSliderDTO);
            }
            catch (Exception ex)
            {
                // Log the exception (ex) here if necessary
                return View("EditSlider", ex.Message);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditSliderAsync(Guid id, CreateSliderDTO updateSliderDTO)
        {
            if (!ModelState.IsValid)
            {
                return View(updateSliderDTO);
            }


            await _SliderService.EditSlider(id, updateSliderDTO);
            TempData["Success"] = "Slider updated successfully!";
            return RedirectToAction("Index");

        }

    }
}

Botanical/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace Botanical.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Botanical/Controllers/ProductController.cs
using Business.DTOs.Products;
using Business.IServices;
using Business.Services;
using Data.Services;
using Microsoft.AspNetCore.Mvc;

namespace Botanical.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductServiceForPresentation _productServiceForPresentation;

        public ProductController(IProductServiceForPresentation productServiceForPresentation)
        {
            _productServiceForPresentation = productServiceForPresentation;       
        }
        public async Task<IActionResult> Detail(Guid id)
        {
            var product = await _productServiceForPresentation.ProductDetail(id);
            if (product == null)
                return NotFound();

            return View(product); 
        }


        [HttpPost]
        public IActionResult DailyDeal()
        {
            var startDate = new DateTime(DateTime.Today.Year, DateTime.Today.Month, DateTime.Today.Day, 0, 0, 0);
            var endDate = startDate.AddDays(1);

            ViewBag.StartDate = startDate;
            ViewBag.EndDate = endDate;

            return View("Index", "Home");
        }

        public async Task<IActionResult> Search(string search)
        {
            var products = await _productServiceForPresentation.Search(search);

            return PartialView("_SearchPartial", products ?? new List<GetProductDTO>());
        }
    }
}

Botanical/Areas/Admin/Views/Shared/Sections/Menu/_VerticalMenu.cshtml
@{
    TempData.Keep();
    string? currentPage = ViewContext.HttpContext.Request.Path;
}

<!-- Menu -->
@* ! Do this simple *@
<aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">

    @* ! Hide app brand if navbar-full *@
    <div class='app-brand demo'>
        <a asp-controller="Dashboards" asp-action="Index" class="app-brand-link">
            <h4 class="m-0 text-primary"><i class="fa fa-book me-3"></i>Botanical</h4>
        </a>

        <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto">
            <i class="menu-toggle-icon d-xl-block align-middle"></i>
        </a>
    </div>

    <div class="menu-inner-shadow"></div>

    @* ! Full version menu-items *@
    <ul class="menu-inner py-1">
        <!-- Dashboards -->
        <li class='menu-item@(currentPage == "/Tables/Basic" ? " active" : "")'>
            <a asp-controller="Dashboards" asp-action="Index" class="menu-link">
                <i class="menu-icon tf-icons ri-home-smile-line"></i>
                <div>Dashboard</div>
            </a>
        </li>

        <!-- Layouts -->

        <li class='menu-item@(currentPage == "/LayoutExamples/WithoutMenu" ? " active" : "")'>
            <a asp-controller="Language" asp-action="Create" class="menu-link">
                <div>Add Language</div>
            </a>
        </li>

        <li class='menu-item@(currentPage.StartsWith("/LayoutExamples") ? " active open" : "")'>
        <li class='menu-item@(currentPage == "/LayoutExamples/WithoutNavbar" ? " active" : "")'>
            <a asp-controller="Category" asp-action="Index" class="menu-link">
                <div>Categories</div>
            </a>
        </li>

        <li class='menu-item@(currentPage == "/LayoutExamples/WithoutNavbar" ? " active" : "")'>
            <a asp-controller="Product" asp-action="Index" class="menu-link">
                <div>Product</div>
            </a>
        </li>

        <li class='menu-item@(currentPage == "/LayoutExamples/WithoutNavbar" ? " active" : "")'>
            <a asp-controller="Slider" asp-action="Index" class="menu-link">
                <div>Sliders</div>
            </a>
        </li>

        <li class='menu-item@(currentPage == "/LayoutExamples/WithoutNavbar" ? " active" : "")'>
            <a asp-controller="Contact" asp-action="Index" class="menu-link">
                <div>Contact</div>
            </a>
        </li>
        <li class='menu-item@(currentPage == "/LayoutExamples/WithoutNavbar" ? " active" : "")'>
            <a asp-controller="Settings" asp-action="Index" class="menu-link">
                <div>Settings</div>
            </a>
        </li>


        <li class="menu-header mt-7">
            <span class="menu-header-text">Apps &amp; Pages</span>
        </li>
        <!-- Apps -->
            @*         <li class='menu-item@(currentPage == "/Apps/Email" ? " active" : "")'>
            <a href="" target="_blank" class="menu-link">
                <i class="menu-icon tf-icons ri-mail-open-line"></i>
                <div>Email</div>
            </a>
        </li> *@

        <!-- Pages -->
            @*   <li class='menu-item@(currentPage.StartsWith("/User") ? " active open" : "")'>
        <a href="javascript:void(0);" class="menu-link menu-toggle">
            <i class="menu-icon tf-icons ri-layout-left-line"></i>
            <div>Account Settings</div>
        </a>
        <ul class="menu-sub">
            <li class='menu-item@(currentPage == "/User/Login" ? " active" : "")'>
                <a asp-controller="User" asp-action="LogOut" class="menu-link">
                    <div>LogOut</div>
                </a>
            </li> *@
            @* <li class='menu-item@(currentPage == "/User/AccountSettingsNotifications" ? " active" : "")'>
            <a asp-controller="Pages" asp-action="AccountSettingsNotifications" class="menu-link">
                <div>Notifications</div>
            </a>
        </li>
        <li class='menu-item@(currentPage == "/User/AccountSettingsConnections" ? " active" : "")'>
            <a asp-controller="Pages" asp-action="AccountSettingsConnections" class="menu-link">
                <div>Connections</div>
            </a>
        </li> *@
    </ul>
    @* </li> *@
    @*         <li class='menu-item@(currentPage.StartsWith("/Pages/Misc") ? " active open" : "")'>
            <a href="javascript:void(0);" class="menu-link menu-toggle">
                <i class="menu-icon tf-icons ri-box-3-line"></i>
                <div>Misc</div>
            </a>
            <ul class="menu-sub">
                <li class='menu-item@(currentPage == "/Pages/MiscError" ? " active" : "")'>
                    <a asp-controller="Pages" asp-action="MiscError" class="menu-link" target="_blank">
                        <div>Error</div>
                    </a>
                </li>
            </ul>
        </li> *@
</aside>
<!-- / Menu -->